name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  python-sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (app)
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Compile Python files
        run: |
          python -m compileall -q app

      - name: Streamlit version
        run: streamlit --version

      - name: Lint with ruff (optional)
        run: |
          pip install ruff
          ruff --version
          ruff check app || true  # non-blocking for POC
